version: "3.8"

x-build-ags: &default-build-ags
  DOCKER_BUILD_DEBUG_VERBOSE: ${DOCKER_BUILD_DEBUG_VERBOSE}
  IMAGE_VERSION: ${IMAGE_VERSION}

x-centos: &default-centos-image
  build:
    args:
      <<: *default-build-ags
    context: .
    dockerfile: Dockerfile
  working_dir: ${APP_USER_HOME}/${APP_USER}
  tty: true
  stdin_open: true

services:
  centos:
    << : *default-centos-image
    image: ${DOCKER_REGISTRY_WORKSTATION}${IMAGE_NAME}:${IMAGE_VERSION}${VERSION_HASH}
    container_name: ${DOCKER_REGISTRY_WORKSTATION}${IMAGE_NAME}:${IMAGE_VERSION}${VERSION_HASH}
